controller_server:
  ros__parameters:
    # Параметры ускорения робота
    acc_lim_theta: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    
    # Параметры скорости робота
    max_vel_x: 0.5
    min_vel_x: 0.05
    max_vel_theta: 1.0
    min_in_place_vel_theta: 0.1
    
    # Голономный робот (false для дифференциального привода)
    holonomic_robot: false
    
    # Допуски для достижения цели
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.05
    
    # Параметры симуляции траекторий
    sim_time: 1.7
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 20
    
    # Параметры оценки траекторий
    goal_distance_bias: 0.8
    path_distance_bias: 0.6
    inflation_cost_scaling_factor: 0.01
    
    # Использовать DWA (Dynamic Window Approach)
    use_dwa: true
    
    # Дистанция для сброса флага колебаний
    oscillation_reset_dist: 0.05
    
    # Обрезать план по мере движения
    prune_plan: true