# Общие параметры для глобальной и локальной карт стоимости
costmap:
  ros__parameters:
    # Тип карты (voxel для 3D)
    map_type: voxel
    
    # Параметры воксельной сетки
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    unknown_threshold: 9
    mark_threshold: 0
    
    # Допуск для TF преобразований
    transform_tolerance: 0.3
    
    # Параметры обнаружения препятствий
    obstacle_range: 2.5
    max_obstacle_height: 2.0
    raytrace_range: 3.0
    
    # Контур робота и отступ
    footprint: "[[-0.22, -0.19], [-0.22, 0.19], [0.22, 0.19], [0.22, -0.19]]"
    footprint_padding: 0.1
    
    # Параметры функции стоимости
    inflation_radius: 2.0
    cost_scaling_factor: 20.0
    
    # Порог стоимости для препятствий
    lethal_cost_threshold: 100
    
    # Источники данных датчиков
    observation_sources: "base_scan"
    base_scan:
      data_type: "LaserScan"
      topic: "/scan"
      marking: true
      clearing: true
      max_obstacle_height: 0.4
      min_obstacle_height: 0.08