global_costmap:
  ros__parameters:
    # Системы координат
    global_frame: "map"
    robot_base_frame: "base_link"
    
    # Частота обновления
    update_frequency: 5.0
    publish_frequency: 0.0
    
    # Использовать статическую карту
    static_map: true
    rolling_window: false
    
    footprint_padding: 0.02