local_costmap:
  ros__parameters:
    # Публиковать воксельную сетку
    publish_voxel_map: true
    
    # Системы координат
    global_frame: "odom"
    robot_base_frame: "base_link"
    
    # Частота обновления
    update_frequency: 5.0
    publish_frequency: 2.0
    
    # Окно, следующее за роботом
    static_map: false
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.025